services:
  db:
    image: postgres
    restart: always
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: leafcatch_development
    volumes:
      - leaf_catch_postgresql_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "bundle install && bundle exec rails db:prepare && rm -f tmp/pids/server.pid && ./bin/dev"
    tty: true
    stdin_open: true
    volumes:
      - .:/leafcatch
      - leaf_catch_bundle_data:/usr/local/bundle:cached
      - leaf_catch_node_modules:/leafcatch/node_modules
    environment:
      TZ: Asia/Tokyo
    ports:
      - "3001:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  leaf_catch_bundle_data:
  leaf_catch_postgresql_data:
  leaf_catch_node_modules: